version: "3"

services:
  next:
    container_name: next
    env_file: .env
    environment:
      - HTTP_PORT=${HTTP_PORT:-3000}
    image: rabbotio/nap
    restart: always
    links:
      - redis
      - mongo
    working_dir: /usr/app
    ports:
      - "5858:5858" # Node Inspector port
      - "3000:${HTTP_PORT:-3000}" # HTTP port
    volumes:
      - ${SRC_NEXT_PAGES:-./pages}:/usr/app/pages
      - ${SRC_NEXT_COMPONENTS:-./components}:/usr/app/components
      - ${SRC_NEXT_STATIC:-./static}:/usr/app/static
      - ${SRC_NEXT_LIB:-./lib}:/usr/app/lib
      - ${SRC_MONGOOSE_MODELS:-./models}:/usr/app/models
    build: .
    command: npm run build-back # Will build next and run express server
    networks:
      - front
      - back

  redis:
    image: redis:3.2.6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis:/data
    networks:
      - back

  mongo_data:  
    image: mongo:3.4
    container_name: mongo_data
    command: bin/true
    networks:
      - back

  mongo:  
    image: mongo:3.4
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: always
    command: --smallfiles --rest
    networks:
      - back

networks:
  front:
  back:

volumes:
  redis:
  mongo_data: