version: "3"

services:
  nap:
    container_name: nap
    env_file: .env
    environment:
      - HTTP_PORT=${HTTP_PORT:-3000}
    image: rabbotio/nap
    restart: always
    links:
      - redis
      - mongo
    working_dir: /usr/app
    ports:
      - "5858:5858" # Node Inspector port
      - "${HTTP_PORT:-3000}:${HTTP_PORT:-3000}" # HTTP port
    volumes:
      - ./.env:/usr/app/.env
      - ${SRC_NEXT_PAGES:-./pages}:/usr/app/pages
      - ${SRC_NEXT_COMPONENTS:-./components}:/usr/app/components
      - ${SRC_NEXT_STATIC:-./public}:/usr/app/public
      - ${SRC_NEXT_LIB:-./lib}:/usr/app/lib
      - ${SRC_MONGOOSE_ROUTES:-./routes}:/usr/app/routes
      - ${SRC_MONGOOSE_MODELS:-./models}:/usr/app/models
      - ${SRC_PASSPORT_PROVIDERS-./providers}:/usr/app/providers # __DEV__
      - ${SRC_SERVER:-./server}:/usr/app/server # __DEV__
    build: .
    command: npm run _build-back # Will build next and run express server
    networks:
      - front
      - back

  redis:
    image: redis:3.2.6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - back

  mongo_data:  
    image: mongo:3.4
    container_name: mongo_data
    command: bin/true
    networks:
      - back

  mongo:  
    image: mongo:3.4
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: always
    command: --smallfiles --rest
    networks:
      - back

networks:
  front:
  back:

volumes:
  redis_data:
  mongo_data: