version: "3"

services:
  next:
    container_name: next
    env_file:
      - ./app/.env
    environment:
      - HTTP_PORT=${HTTP_PORT:-3000}
    build: ./app
    restart: always
    links:
      - redis
      - mongo
    command: npm start
    working_dir: /usr/app
    volumes:
      - app:/app
    ports:
      - "127.0.0.1:9229:9229" # V8 inspector
      - "3000:3000"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier

  redis:
    image: redis:3.2.6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis:/data
    networks:
      - back-tier

  mongo_data:  
    image: mongo:3.4
    container_name: mongo_data
    command: bin/true
    networks:
      - back-tier

  mongo:  
    image: mongo:3.4
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    command: --smallfiles --rest
    networks:
      - back-tier

networks:
  front-tier:
  back-tier:

volumes:
  app:
  redis:
  mongo_data: